version: '3.8'
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-94!@xyjzw#$$jdu4m4p@v9#gnk&m(en=*w*773$$w$@t_!()a$$es"
      - "DJANGO_DEBUG=True"
      - "SOCIAL_AUTH_GITHUB_KEY=7da4cb5692bfb892d919"
      - "SOCIAL_AUTH_GITHUB_SECRET=042629f277b29fc8267178e1f762691e700e87c7"
  db:
    image: postgres
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:
